on:
  push:
    branches:
      - "master"
  
jobs:
  build:
    strategy:
      matrix:
        config: [Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Build solution
        run: dotnet build -c "Release" 